


CREATE DATABASE IF NOT EXISTS `promptpayqr`;

CREATE TABLE `saveQr` (
  `id` int(11) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  `amount` int(20) NOT NULL,
  `qrcode` LONGBLOB NOT NULL,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

ALTER TABLE `saveQr`
  MODIFY `id` int(11) AUTO_INCREMENT;
